#!/bin/sh
# =============================================================================
# hemostart Installation Script
# Generated by shinstall.js
# Version: 2.0 - Enhanced with Forced Online Dependency Installation
# =============================================================================


PROJECT_NAME="hemostart"
INSTALL_DIR="/usr/local/etc/hemostart"
BIN_DIR="/usr/local/bin"
REPO_DIR=$(pwd)
MAIN_SOURCE_DIR="."
BACKUP_DIR="${INSTALL_DIR}_old_$(date +%s)"


# Main entry point mapping
MAIN_ENTRY_POINT_SRC="HemoStart.java"
MAIN_ENTRY_POINT_CMD="hemostart"


# =============================================================================
# ONLINE DEPENDENCY INSTALLATION (auto-generated)
# =============================================================================
ONLINE_MODE=false

# Helper: check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Helper: install packages via apt
install_apt() {
    echo "Installing via apt: $*"
    sudo apt update && sudo apt install -y "$@"
}

# Helper: install packages via apk
install_apk() {
    echo "Installing via apk: $*"
    apk add --no-cache "$@"
}

# Install dependencies for a specific language
install_language_dependency() {
    lang="$1"
    echo "Checking dependencies for $lang..."
    case "$lang" in
        nodejs)
            if ! command_exists node; then
                echo "Node.js not found. Installing..."
                if command_exists apt; then install_apt nodejs;
                elif command_exists apk; then install_apk nodejs npm;
                else echo "No supported package manager found."; return 1; fi
            else
                echo "Node.js already installed."
            fi
            ;;
        python)
            if ! command_exists python3; then
                echo "Python3 not found. Installing..."
                if command_exists apt; then install_apt python3;
                elif command_exists apk; then install_apk python3;
                else echo "No supported package manager found."; return 1; fi
            else
                echo "Python3 already installed."
            fi
            ;;
        c)
            if ! command_exists gcc; then
                echo "GCC not found. Installing..."
                if command_exists apt; then install_apt gcc;
                elif command_exists apk; then install_apk build-base;
                else echo "No supported package manager found."; return 1; fi
            else
                echo "GCC already installed."
            fi
            ;;
        cpp)
            if ! command_exists g++; then
                echo "G++ not found. Installing..."
                if command_exists apt; then install_apt g++;
                elif command_exists apk; then install_apk g++;
                else echo "No supported package manager found."; return 1; fi
            else
                echo "G++ already installed."
            fi
            ;;
        java)
            if ! command_exists javac || ! command_exists java; then
                echo "Java not found. Installing..."
                if command_exists apt; then install_apt default-jdk;
                elif command_exists apk; then install_apk openjdk11;
                else echo "No supported package manager found."; return 1; fi
            else
                echo "Java already installed."
            fi
            ;;
        shell)
            echo "Shell scripts need no special runtime."
            ;;
        unknown)
            echo "Unknown language - skipping dependency installation."
            ;;
    esac
    return 0
}

# Install all language dependencies (main + additional tools)
install_language_deps() {
    [ "$ONLINE_MODE" = true ] || return 0
    echo "=== Checking and installing language dependencies ==="
    
    # Main entry point
    main_src="$MAIN_ENTRY_POINT_SRC"
    if [ -n "$main_src" ]; then
        main_lang=$(detect_language "$main_src")
        echo "Main command ($MAIN_ENTRY_POINT_CMD) uses: $main_lang"
        install_language_dependency "$main_lang"
    fi
    
    # Additional tool commands
    if [ -n "$ADDITIONAL_TOOL_SRC" ]; then
        echo "Checking additional tool commands..."
        idx=1
        for src in $ADDITIONAL_TOOL_SRC; do
            cmd=$(echo "$ADDITIONAL_TOOL_CMD" | tr ' ' '\n' | sed -n "${idx}p")
            [ -z "$cmd" ] && continue
            tool_lang=$(detect_language "$src")
            echo "Tool command '$cmd' uses: $tool_lang"
            install_language_dependency "$tool_lang"
            idx=$((idx + 1))
        done
    fi
    
    echo "=== Language dependencies check completed ==="
}


# =============================================================================
# MULTI-LANGUAGE SUPPORT (always available)
# =============================================================================

# Detect language from file extension
detect_language() {
    file_path="$1"
    ext="${file_path##*.}"
    case "$ext" in
        js|mjs|cjs) echo "nodejs" ;;
        py|py3) echo "python" ;;
        c) echo "c" ;;
        cpp|cc|cxx|hpp) echo "cpp" ;;
        java) echo "java" ;;
        sh|bash) echo "shell" ;;
        *) echo "unknown" ;;
    esac
}

# Create command wrapper for a specific language
create_language_command() {
    src_path="$1"
    cmd_name="$2"
    src_name="$3"
    lang=$(detect_language "$src_name")
    
    wrapper="$INSTALL_DIR/wrappers/$cmd_name"
    mkdir -p "$INSTALL_DIR/wrappers"
    
    case "$lang" in
        nodejs)
            # Node.js
            cat > "$wrapper" << EOF
#!/bin/sh
exec node "$src_path" "\$@"
EOF
            ;;
        python)
            # Python
            cat > "$wrapper" << EOF
#!/bin/sh
exec python3 "$src_path" "\$@"
EOF
            ;;
        c)
            # C: compile to binary in $INSTALL_DIR/bin
            bin_path="$INSTALL_DIR/bin/$cmd_name"
            mkdir -p "$INSTALL_DIR/bin"
            echo "Compiling C program: $src_name -> $cmd_name"
            if command_exists gcc; then
                gcc -o "$bin_path" "$src_path" || { echo "Compilation failed for $src_name"; return 1; }
            else
                echo "Error: gcc not found. Use --online to install dependencies."
                return 1
            fi
            cat > "$wrapper" << EOF
#!/bin/sh
exec "$bin_path" "\$@"
EOF
            ;;
        cpp)
            # C++
            bin_path="$INSTALL_DIR/bin/$cmd_name"
            mkdir -p "$INSTALL_DIR/bin"
            echo "Compiling C++ program: $src_name -> $cmd_name"
            if command_exists g++; then
                g++ -o "$bin_path" "$src_path" || { echo "Compilation failed for $src_name"; return 1; }
            else
                echo "Error: g++ not found. Use --online to install dependencies."
                return 1
            fi
            cat > "$wrapper" << EOF
#!/bin/sh
exec "$bin_path" "\$@"
EOF
            ;;
        java)
            # Java: compile to .class files in $INSTALL_DIR/classes
            classes_dir="$INSTALL_DIR/classes"
            mkdir -p "$classes_dir"
            echo "Compiling Java program: $src_name -> $cmd_name"
            if command_exists javac; then
                javac -d "$classes_dir" "$src_path" || { echo "Compilation failed for $src_name"; return 1; }
            else
                echo "Error: javac not found. Use --online to install dependencies."
                return 1
            fi
            main_class=$(basename "$src_name" .java)
            cat > "$wrapper" << EOF
#!/bin/sh
exec java -cp "$classes_dir" "$main_class" "\$@"
EOF
            ;;
        shell)
            # Shell script: make executable and link directly
            echo "Setting up shell script: $src_name -> $cmd_name"
            chmod +x "$src_path"
            wrapper="$src_path"
            ;;
        unknown)
            echo "Unknown language for $src_name - trying with shebang..."
            # Fallback: try to use shebang from the file
            if head -1 "$src_path" | grep -q '^#!'; then
                chmod +x "$src_path"
                wrapper="$src_path"
            else
                echo "Error: Cannot determine how to execute $src_name"
                return 1
            fi
            ;;
    esac
    
    if [ "$wrapper" != "$src_path" ]; then
        chmod +x "$wrapper"
        ln -sf "$wrapper" "$BIN_DIR/$cmd_name"
    else
        ln -sf "$src_path" "$BIN_DIR/$cmd_name"
    fi
    echo "Created command: $cmd_name -> $src_path (language: $lang)"
    return 0
}

# Core functions
# =============================================================================
# CORE FUNCTIONS
# =============================================================================
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
}

copy_files() {
    mkdir -p "$INSTALL_DIR"
    echo "Copying files..."
    (cd "$MAIN_SOURCE_DIR" && find . -type f -not -path '*/.git/*' -exec cp --parents {} "$INSTALL_DIR" \;)
}

create_command_links() {
    echo "Creating command links with language detection..."
    
    # Create main command
    main_src="$MAIN_ENTRY_POINT_SRC"
    main_cmd="$MAIN_ENTRY_POINT_CMD"
    
    if [ -n "$main_src" ] && [ -n "$main_cmd" ]; then
        src_path="$INSTALL_DIR/$main_src"
        if [ -f "$src_path" ]; then
            create_language_command "$src_path" "$main_cmd" "$main_src"
        else
            echo "Warning: Main source file not found: $src_path"
        fi
    fi
    
    # Create additional tool commands
    if [ -n "$ADDITIONAL_TOOL_SRC" ]; then
        idx=1
        for src in $ADDITIONAL_TOOL_SRC; do
            cmd=$(echo "$ADDITIONAL_TOOL_CMD" | tr ' ' '\n' | sed -n "${idx}p")
            [ -z "$cmd" ] && continue
            src_path="$INSTALL_DIR/$src"
            if [ -f "$src_path" ]; then
                create_language_command "$src_path" "$cmd" "$src"
            else
                echo "Warning: Tool source file not found: $src_path"
            fi
            idx=$((idx + 1))
        done
    fi
}

remove_links() {
    # Remove main command
    [ -L "$BIN_DIR/$MAIN_ENTRY_POINT_CMD" ] && rm -f "$BIN_DIR/$MAIN_ENTRY_POINT_CMD"
    
    # Remove additional tool commands
    if [ -n "$ADDITIONAL_TOOL_CMD" ]; then
        for cmd in $ADDITIONAL_TOOL_CMD; do
            [ -L "$BIN_DIR/$cmd" ] && rm -f "$BIN_DIR/$cmd"
        done
    fi
    
    # Remove generated directories
    [ -d "$INSTALL_DIR/wrappers" ] && rm -rf "$INSTALL_DIR/wrappers"
    [ -d "$INSTALL_DIR/bin" ] && rm -rf "$INSTALL_DIR/bin"
    [ -d "$INSTALL_DIR/classes" ] && rm -rf "$INSTALL_DIR/classes"
}

execute_post_install_scripts() {
    [ -z "$POST_INSTALL_SCRIPTS" ] && return 0
    echo "Executing post-install scripts..."
    cd "$INSTALL_DIR"
    for script in $POST_INSTALL_SCRIPTS; do
        [ -f "$script" ] && sh "$script"
    done
    cd - >/dev/null
}

cleanup() {
    sudo dpkg --configure -a >/dev/null 2>&1 || true
}

show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo "Install $PROJECT_NAME"
    echo ""
    echo "Options:"
    echo "  -h, --help       Show this help"
    echo "  --online         Install missing language dependencies"
    echo "  --force          Force update without asking"
    echo "  --remove         Remove existing installation"
    echo ""
    echo "Commands created:"
    echo "  $MAIN_ENTRY_POINT_CMD"
    if [ -n "$ADDITIONAL_TOOL_CMD" ]; then
        for cmd in $ADDITIONAL_TOOL_CMD; do
            echo "  $cmd"
        done
    fi
}


# Parse arguments
FORCE_UPDATE=false
FORCE_REMOVE=false
while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help) show_help; exit 0 ;;
        --online) ONLINE_MODE=true ;;
        --no-online) ONLINE_MODE=false ;;
        --build) BUILD_MODE=true ;;
        --tar) BUILD_TAR=true ;;
        --config) BUILD_CONFIG=true ;;
        --message) BUILD_MESSAGE_MODE=true ;;
        --force|-f) FORCE_UPDATE=true ;;
        --remove|-r) FORCE_REMOVE=true ;;
        *) ;;
    esac
    shift
done


# Check if already installed
if [ -d "$INSTALL_DIR" ]; then
    if [ "$FORCE_REMOVE" = true ]; then
        echo "Removing existing installation..."
        remove_links
        rm -rf "$INSTALL_DIR"
        echo "Removed. Proceeding with fresh install..."
    elif [ "$FORCE_UPDATE" = true ]; then
        echo "Forcing update..."
        mv -f "$INSTALL_DIR" "$BACKUP_DIR"
        remove_links
        echo "Proceeding with update..."
    else
        echo "Existing installation found at $INSTALL_DIR"
        echo ""
        echo "Choose an option:"
        echo "  1. Update (replace existing files)"
        echo "  2. Remove (delete existing installation)"
        echo "  3. Exit"
        printf "Enter your choice (1/2/3): "
        read choice
        case "$choice" in
            1)
                echo "Updating..."
                mv -f "$INSTALL_DIR" "$BACKUP_DIR"
                remove_links
                ;;
            2)
                echo "Removing..."
                remove_links
                rm -rf "$INSTALL_DIR"
                echo "Removed successfully."
                exit 0
                ;;
            3)
                echo "Exiting."
                exit 0
                ;;
            *)
                echo "Invalid choice. Exiting."
                exit 1
                ;;
        esac
    fi
fi


# Install missing language dependencies if --online was passed
install_language_deps


# Create installation directory and copy files
copy_files


# Create command links (with language detection)
create_command_links


# Execute post-install scripts
execute_post_install_scripts

cleanup

echo ""
echo "Installation completed!"
echo ""
echo "Available commands:"
echo "  $MAIN_ENTRY_POINT_CMD"
if [ -n "$ADDITIONAL_TOOL_CMD" ]; then
    for cmd in $ADDITIONAL_TOOL_CMD; do
        echo "  $cmd"
    done
fi
echo ""
echo "Installation directory: $INSTALL_DIR"
