#!/bin/sh
# =============================================================================
# hemostart Installation Script
# Generated by shinstall.js
# =============================================================================


PROJECT_NAME="hemostart"
INSTALL_DIR="/usr/local/etc/hemostart"
BIN_DIR="/usr/local/bin"
REPO_DIR=$(pwd)
MAIN_SOURCE_DIR="."
MAIN_ENTRY_POINTS_SRC="HemoStart.java"
MAIN_ENTRY_POINTS_CMD="hemostart"


SUDO=""
if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
fi


# =============================================================================
# AUTO LANGUAGE DETECTION & DEPENDENCIES  (idempotent)
# =============================================================================
INSTALL_DEPS=true
APT_UPDATED=false

have_cmd() { command -v "$1" >/dev/null 2>&1; }

# Is a package already installed?  Try the native package manager first.
pkg_installed() {
    pkg="$1"
    if have_cmd dpkg;   then dpkg -s "$pkg"       >/dev/null 2>&1 && return 0; fi
    if have_cmd rpm;    then rpm -q "$pkg"        >/dev/null 2>&1 && return 0; fi
    if have_cmd apk;    then apk info -e "$pkg"   >/dev/null 2>&1 && return 0; fi
    if have_cmd pacman; then pacman -Q  "$pkg"    >/dev/null 2>&1 && return 0; fi
    return 1
}

# Run apt-get update at most once per install.sh invocation, and only
# when we're actually about to install something.
apt_update_once() {
    [ "$APT_UPDATED" = "true" ] && return 0
    APT_UPDATED=true
    if have_cmd apt-get; then $SUDO apt-get update -qq
    elif have_cmd apt;   then $SUDO apt update -qq
    fi
}

# Install the given packages, skipping any that are already present.
install_packages() {
    [ $# -eq 0 ] && return 0
    to_install=""
    for pkg in "$@"; do
        if pkg_installed "$pkg"; then
            echo "    already installed: $pkg"
        else
            echo "    MISSING:           $pkg"
            to_install="$to_install $pkg"
        fi
    done
    if [ -z "$to_install" ]; then
        echo "    -> nothing to install"
        return 0
    fi
    echo "    -> installing:$to_install"
    apt_update_once
    if have_cmd apt-get; then $SUDO apt-get install -y $to_install
    elif have_cmd apt;   then $SUDO apt install -y $to_install
    elif have_cmd apk;   then $SUDO apk add $to_install
    elif have_cmd dnf;   then $SUDO dnf install -y $to_install
    elif have_cmd yum;   then $SUDO yum install -y $to_install
    elif have_cmd pacman; then $SUDO pacman -S --noconfirm $to_install
    else echo "    no supported package manager; install manually:$to_install"; return 1
    fi
}

# Skip if the toolchain commands are already present; otherwise check
# the package manager, then install only the missing packages.
install_language_deps() {
    lang="$1"
    case "$lang" in
        node)
            if have_cmd node && have_cmd npm; then
                echo "    node/npm: present at $(command -v node)"; return 0
            fi
            install_packages nodejs npm ;;
        python)
            if have_cmd python3; then
                echo "    python3: present at $(command -v python3)"; return 0
            fi
            install_packages python3 ;;
        ruby)
            if have_cmd ruby; then
                echo "    ruby:    present at $(command -v ruby)"; return 0
            fi
            install_packages ruby ;;
        php)
            if have_cmd php; then
                echo "    php:     present at $(command -v php)"; return 0
            fi
            install_packages php-cli php ;;
        perl)
            if have_cmd perl; then
                echo "    perl:    present at $(command -v perl)"; return 0
            fi
            install_packages perl ;;
        shell)
            if have_cmd bash; then
                echo "    bash:    present at $(command -v bash)"; return 0
            fi
            install_packages bash ;;
        java)
            if have_cmd javac && have_cmd java; then
                echo "    javac:   present at $(command -v javac)"; return 0
            fi
            install_packages default-jdk ;;
        c)
            if have_cmd gcc; then
                echo "    gcc:     present at $(command -v gcc)"; return 0
            fi
            install_packages build-essential gcc ;;
        cpp)
            if have_cmd g++; then
                echo "    g++:     present at $(command -v g++)"; return 0
            fi
            install_packages build-essential g++ ;;
        go)
            if have_cmd go; then
                echo "    go:      present at $(command -v go)"; return 0
            fi
            install_packages golang-go ;;
        rust)
            if have_cmd rustc; then
                echo "    rustc:   present at $(command -v rustc)"; return 0
            fi
            install_packages rustc cargo ;;
    esac
}


# =============================================================================
# CORE HELPERS
# =============================================================================
detect_language() {
    case "$1" in
        *.js|*.mjs|*.cjs|*.ts)    echo "node" ;;
        *.py)                     echo "python" ;;
        *.rb)                     echo "ruby" ;;
        *.php)                    echo "php" ;;
        *.pl)                     echo "perl" ;;
        *.sh)                     echo "shell" ;;
        *.java)                   echo "java" ;;
        *.c|*.h)                  echo "c" ;;
        *.cpp|*.cc|*.cxx|*.hpp)   echo "cpp" ;;
        *.go)                     echo "go" ;;
        *.rs)                     echo "rust" ;;
        *)                        echo "unknown" ;;
    esac
}

link_cmd() {
    target="$1"; name="$2"
    if [ -w "$BIN_DIR" ]; then
        ln -sf "$target" "$BIN_DIR/$name"
    else
        $SUDO ln -sf "$target" "$BIN_DIR/$name"
    fi
}

copy_files() {
    src_dir="$1"; dst_dir="$2"
    [ -d "$src_dir" ] || { echo "Source dir not found: $src_dir"; return 1; }
    mkdir -p "$dst_dir"
    echo "Copying files from $src_dir to $dst_dir..."
    cp -R "$src_dir"/. "$dst_dir"/ 2>/dev/null || true
    rm -rf "$dst_dir/.git" "$dst_dir/node_modules"
}

remove_links() {
    cmd_list="$MAIN_ENTRY_POINTS_CMD"
    for cmd in $cmd_list; do
        [ -L "$BIN_DIR/$cmd" ] && $SUDO rm -f "$BIN_DIR/$cmd"
    done
    [ -d "$INSTALL_DIR/wrappers" ] && rm -rf "$INSTALL_DIR/wrappers"
}

execute_post_install_scripts() {
    [ -z "$POST_INSTALL_SCRIPTS" ] && return 0
    echo "Executing post-install scripts..."
    cd "$INSTALL_DIR" || return 0
    for script in $POST_INSTALL_SCRIPTS; do
        [ -f "$script" ] && sh "$script"
    done
    cd - >/dev/null 2>&1 || true
}

cleanup() {
    $SUDO dpkg --configure -a >/dev/null 2>&1 || true
}


# =============================================================================
# COMPILE STEP (once, at install time)
# =============================================================================
compile_entry() {
    lang="$1"; src="$2"; out="$3"
    case "$lang" in
        c)    command -v gcc   >/dev/null 2>&1 || { echo "  gcc missing";   return 1; }; gcc   -O2 -o "$out" "$src" ;;
        cpp)  command -v g++   >/dev/null 2>&1 || { echo "  g++ missing";   return 1; }; g++   -O2 -o "$out" "$src" ;;
        go)   command -v go    >/dev/null 2>&1 || { echo "  go missing";    return 1; }; go    build -o "$out" "$src" ;;
        rust) command -v rustc >/dev/null 2>&1 || { echo "  rustc missing"; return 1; }; rustc -O   -o "$out" "$src" ;;
        java) command -v javac >/dev/null 2>&1 || { echo "  javac missing"; return 1; }; javac -d "$(dirname "$src")" "$src" ;;
        *)    return 0 ;;
    esac
}

build_compiled_entries() {
    mkdir -p "$INSTALL_DIR/bin"
    idx=1
    for src in $MAIN_ENTRY_POINTS_SRC; do
        cmd=$(echo "$MAIN_ENTRY_POINTS_CMD" | tr ' ' '\n' | sed -n "${idx}p")
        [ -z "$cmd" ] && { idx=$((idx+1)); continue; }
        src_path="$INSTALL_DIR/$src"
        [ ! -f "$src_path" ] && { idx=$((idx+1)); continue; }
        lang=$(detect_language "$src_path")
        case "$lang" in
            c|cpp|go|rust)
                out="$INSTALL_DIR/bin/$cmd"
                echo "Compiling $src_path -> $out"
                compile_entry "$lang" "$src_path" "$out" || true
                ;;
            java)
                echo "Compiling Java source $src_path"
                compile_entry "java" "$src_path" "" || true
                ;;
        esac
        idx=$((idx+1))
    done
}


# =============================================================================
# COMMAND WRAPPERS (never compile here)
# =============================================================================
create_command_links() {
    mkdir -p "$INSTALL_DIR/wrappers"
    src_list="$MAIN_ENTRY_POINTS_SRC"
    cmd_list="$MAIN_ENTRY_POINTS_CMD"
    idx=1
    for src in $src_list; do
        cmd=$(echo "$cmd_list" | tr ' ' '\n' | sed -n "${idx}p")
        [ -z "$cmd" ] && { idx=$((idx+1)); continue; }
        src_path="$INSTALL_DIR/$src"
        if [ ! -f "$src_path" ]; then
            echo "  warning: source file not found: $src_path"
            idx=$((idx+1)); continue
        fi
        lang=$(detect_language "$src_path")
        wrapper="$INSTALL_DIR/wrappers/$cmd"
        echo "Creating command '$cmd' for $src_path (language: $lang)"

        case "$lang" in
            node)
                if ! head -1 "$src_path" | grep -q '^#!'; then
                    tmp="$(mktemp)"
                    { echo '#!/usr/bin/env node'; cat "$src_path"; } > "$tmp"
                    mv "$tmp" "$src_path"
                fi
                chmod +x "$src_path"
                cat > "$wrapper" << WRAPEOF
#!/bin/sh
exec node "$src_path" "\$@"
WRAPEOF
                ;;
            python) cat > "$wrapper" << WRAPEOF
#!/bin/sh
exec python3 "$src_path" "\$@"
WRAPEOF
                ;;
            ruby) cat > "$wrapper" << WRAPEOF
#!/bin/sh
exec ruby "$src_path" "\$@"
WRAPEOF
                ;;
            php) cat > "$wrapper" << WRAPEOF
#!/bin/sh
exec php "$src_path" "\$@"
WRAPEOF
                ;;
            perl) cat > "$wrapper" << WRAPEOF
#!/bin/sh
exec perl "$src_path" "\$@"
WRAPEOF
                ;;
            shell) cat > "$wrapper" << WRAPEOF
#!/bin/sh
exec bash "$src_path" "\$@"
WRAPEOF
                ;;
            c|cpp|go|rust)
                binary="$INSTALL_DIR/bin/$cmd"
                if [ -x "$binary" ]; then
                    cat > "$wrapper" << WRAPEOF
#!/bin/sh
exec "$binary" "\$@"
WRAPEOF
                else
                    echo "  error: binary not built for $src_path (compiler missing?)"
                    idx=$((idx+1)); continue
                fi
                ;;
            java)
                cls=$(basename "$src_path" .java)
                cls_dir=$(dirname "$src_path")
                cat > "$wrapper" << WRAPEOF
#!/bin/sh
exec java -cp "$cls_dir" "$cls" "\$@"
WRAPEOF
                ;;
            *)
                chmod +x "$src_path" 2>/dev/null || true
                cat > "$wrapper" << WRAPEOF
#!/bin/sh
exec "$src_path" "\$@"
WRAPEOF
                ;;
        esac
        chmod +x "$wrapper"
        link_cmd "$wrapper" "$cmd"
        echo "  -> $BIN_DIR/$cmd"
        idx=$((idx+1))
    done
}


show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo "Install $PROJECT_NAME"
    echo ""
    echo "Options:"
    echo "  -h, --help       Show this help"
    echo "  --deps           Force dependency installation check"
    echo "  --force, -f      Force update without asking"
    echo "  --remove, -r     Remove existing installation"
    echo ""
    echo "Commands created:"
    for cmd in $MAIN_ENTRY_POINTS_CMD; do
        echo "  $cmd"
    done
}

FORCE_UPDATE=false
FORCE_REMOVE=false
while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)   show_help; exit 0 ;;
        --deps)      INSTALL_DEPS=true ;;
        --force|-f)  FORCE_UPDATE=true ;;
        --remove|-r) FORCE_REMOVE=true ;;
        *) ;;
    esac
    shift
done

if [ -d "$INSTALL_DIR" ]; then
    if [ "$FORCE_REMOVE" = true ]; then
        echo "Removing existing installation..."
        remove_links
        $SUDO rm -rf "$INSTALL_DIR"
        echo "Removed. Proceeding with fresh install..."
    elif [ "$FORCE_UPDATE" = true ]; then
        echo "Forcing update..."
        remove_links
    else
        echo "Existing installation found at $INSTALL_DIR"
        echo "  1. Update (replace existing files)"
        echo "  2. Remove (delete existing installation)"
        echo "  3. Exit"
        printf "Enter your choice (1/2/3): "
        read choice
        case "$choice" in
            1) echo "Updating..."; remove_links ;;
            2)
                echo "Removing..."
                remove_links
                $SUDO rm -rf "$INSTALL_DIR"
                echo "Removed successfully."
                exit 0
                ;;
            *) echo "Exiting."; exit 0 ;;
        esac
    fi
fi


if [ "$INSTALL_DEPS" != "false" ]; then
    echo "Checking language toolchains for entry points..."
    for src in $MAIN_ENTRY_POINTS_SRC; do
        lang=$(detect_language "$src")
        [ "$lang" = "unknown" ] && { echo "  $src: unknown language, skipping"; continue; }
        echo "  $src -> $lang"
        install_language_deps "$lang"
    done
fi


copy_files "$MAIN_SOURCE_DIR" "$INSTALL_DIR"
build_compiled_entries
create_command_links


execute_post_install_scripts
cleanup

echo ""
echo "Installation completed!"
echo ""
echo "Available commands:"
for cmd in $MAIN_ENTRY_POINTS_CMD; do
    echo "  $cmd"
done
echo ""
echo "Installation directory: $INSTALL_DIR"
